---

# Playbook to create VLANs on Cisco Nexus switch from file
- name: Configure vlans
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Provision VLAN
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ item }}"
            state: active
      with_items: "{{ lookup('file', 'vlans.txt').splitlines() }}"
